@startuml RefBase

class RefBase {
    +void incStrong(const void* id) const
    +void incStrongRequireStrong(const void* id) const
    +void decStrong(const void* id) const
    +void forceIncStrong(const void* id) const

    +class weakref_type {}

    #RefBase()
    #virual ~RefBase()

    #virtual void onFirstRef()
    #virtual void onLastStrongRef(const void* id)
    #virtual bool onIncStrongAttempted(uint32_t flags, const void* id)
    #virtual void onLastWeakRef(const void* id)
}

@enduml